PAPERS = [
    {
        "title": "#1880 Novel ai-based recipe recommendation system for dialysis patients using retrieval-augmented generation",
        "semanticscholarid": "4e86254be24e4dcac4d0a0cc2d72d9c0f3e9f6bd",
        "repo": "https://www.freseniuskidneycare.com/recipes-and-nutrition/recipes",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "2OMe-LM: predicting 2′-O-methylation sites in human RNA using a pre-trained RNA language model",
        "semanticscholarid": "949cab640f543f200ad1fbeed56cc1c9519b1251",
        "repo": "https://github.com/CSUBioGroup/2OMe-LM",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "4DLangVGGT: 4D Language-Visual Geometry Grounded Transformer",
        "semanticscholarid": "2841f2f2b548c5f61c06917e07c41caf5c55d414",
        "repo": "https://github.com/hustvl/4DLangVGGT",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "90% Faster, 100% Code-Free: MLLM-Driven Zero-Code 3D Game Development",
        "semanticscholarid": "00c2c1e1c1891a958a3e45158d7fe4b3cac8a515",
        "repo": "https://github.com/yxwan123/UniGen",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Benchmark Dataset and Evaluation Framework for Vietnamese Large Language Models in Customer Support",
        "semanticscholarid": "a308f20ee69717f2fd8544234c07706266d14c7f",
        "repo": "https://huggingface.co/datasets/ura-hcmut/Vietnamese-Customer-Support-QA",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Brain Cell Type Resource Created by Large Language Models and a Multi-Agent AI System for Collaborative Community Annotation",
        "semanticscholarid": "ee5014ad91d8d9443e3acc2aa3e88ef84db8437e",
        "repo": "https://biodataai.uth.edu/BRAINCELL-AID",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Abstract A024: DeepVul: A multi-task transformer model for joint prediction of gene essentiality and drug response",
        "semanticscholarid": "16fac89388bf55d9c418caf1acacd608560780ef",
        "repo": "https://github.com/alaaj27/DeepVul.git",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Abstract A030: Mutation2Text: A unified protein and text language model for explaining mutation effects",
        "semanticscholarid": "6d7f56be14d20152097094fc31a7384b28807ef9",
        "repo": "https://anonymous.4open.science/r/mutation2text-94A6/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Abstract B040: Literature-scaled immunological gene set annotation using AI-powered immune cell knowledge graph (ICKG)",
        "semanticscholarid": "9cebc05a613a4ea264e4bccfd67ff86600e86232",
        "repo": "https://kchen-lab.github.io/immune-knowledgegraph.github.io/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Accelerated Aggregated D-Optimal Designs for Estimating Main Effects in Black-Box Models",
        "semanticscholarid": "100bcd9651bc827400b22c227b6eb87fb3dca1ab",
        "repo": "https://github.com/cchihyu/A2D2E",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AccidentBench: Benchmarking Multimodal Understanding and Reasoning in Vehicle Accidents and Beyond",
        "semanticscholarid": "b78e056bcdba9447459237e8364ddcf3a22040c4",
        "repo": "https://github.com/SafeRL-Lab/AccidentBench",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Comprehensive Evaluation of LLM Reasoning: From Single-Model to Multi-Agent Paradigms",
        "semanticscholarid": "8184cb4b061efd01f3034b9c4d9f8cb14da0d762",
        "repo": "https://gitcode.com/HIT1920/OpenLLMBench",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Comprehensive Survey of Electronic Health Record Modeling: From Deep Learning Approaches to Large Language Models",
        "semanticscholarid": "be7728e1beb6dd5de8de6b36a2fe561845b7e4c1",
        "repo": "https://survey-on-tabular-data.github.io/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Comprehensive Survey on Trustworthiness in Reasoning with Large Language Models",
        "semanticscholarid": "2429de2c3f2b7ddcdf1f8b2d34c6eb8b75cc47f9",
        "repo": "https://github.com/ybwang119/Awesome-reasoning-safety",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Computational Approach to Visual Metonymy",
        "semanticscholarid": "5c8bfe851ea4a1a9ec20dd198ddfbe17f133cc7e",
        "repo": "https://github.com/cincynlp/ViMET",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "ACP-EPC: an interpretable deep learning framework for anticancer peptide prediction utilizing pre-trained protein language model and multi-view feature extracting strategy.",
        "semanticscholarid": "689bb3f20a8b129eae67098367c83118007976bc",
        "repo": "http://www.bioai-lab.com/ACP-EPC",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AdamMeme: Adaptively Probe the Reasoning Capacity of Multimodal Large Language Models on Harmfulness",
        "semanticscholarid": "f94f6822c9fe5046a1818e145677352f99799d57",
        "repo": "https://github.com/Lbotirx/AdamMeme",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Adaptive Graph Learning with Transformer for Multi-Reservoir Inflow Prediction",
        "semanticscholarid": "2ff0de04f14ea6045ddaf469e2b7e321999a96a1",
        "repo": "https://github.com/humphreyhuu/AdaTrip",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Adaptive Obstacle-Aware Task Assignment and Planning for Heterogeneous Robot Teaming",
        "semanticscholarid": "b39e7490bccf708763cb66a599acdf1c4c3a60ed",
        "repo": "https://llm-oath.github.io/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AdaptPNP: Integrating Prehensile and Non-Prehensile Skills for Adaptive Robotic Manipulation",
        "semanticscholarid": "247c95e1073909f468f8ec88f515d4c1451ff3bd",
        "repo": "https://sites.google.com/view/adaptpnp/home",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Addressing Logical Fallacies In Scientific Reasoning From Large Language Models: Towards a Dual-Inference Training Framework",
        "semanticscholarid": "5000db4d66e7884114390c88162811b44fe46c7d",
        "repo": "https://github.com/hannahdavidsoncollege-maker/ScientificReasoningForEnvironment-MedicineWithLLMs",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Dual Large Language Models Architecture with Herald Guided Prompts for Parallel Fine Grained Traffic Signal Control",
        "semanticscholarid": "50cbc8bcd56169388637d6ac6e7390879968da45",
        "repo": "https://github.com/BUPT-ANTlab/HeraldLight",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Advancing ADMET prediction through multiscale fragment-aware pretraining with MSformer-ADMET",
        "semanticscholarid": "f041717fa0bf230cbce34dc8d2e2a51da7ac6770",
        "repo": "https://github.com/ZJUFanLab/MSformer",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Advancing Complex Wide-Area Scene Understanding with Hierarchical Coresets Selection",
        "semanticscholarid": "735e985fe2db5f8b8aa94a8ea2713815193eb58f",
        "repo": "https://wangjingyao07.github.io/HCS.github.io/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Advancing site-specific disease and pest management in precision agriculture: From reasoning-driven foundation models to adaptive, feedback-based learning",
        "semanticscholarid": "d3d800753aceafe767edcb2e1cd2748f54c29dea",
        "repo": "https://github.com/nitin-dominic/AgriPathogenDatabase",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Adversarial Attention Perturbations for Large Object Detection Transformers",
        "semanticscholarid": "8a5e5b5bd4ddf16add90033e8b4394116d71d6d3",
        "repo": "https://github.com/zacharyyahn/AFOG",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A First-Order Logic-Based Alternative to Reward Models in RLHF",
        "semanticscholarid": "3fac01d47dcdfcd2d442d3407180cbd66ade9459",
        "repo": "https://github.com/ChunjinJiang/sgrpo",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A foundation model for learning genetic associations from brain imaging phenotypes",
        "semanticscholarid": "6681151239348eb3e526b9230ce9d8e1db5f0498",
        "repo": "https://github.com/IBM/comical",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Framework for Analyzing Abnormal Emergence in Service Ecosystems Through LLM-Based Agent Intention Mining",
        "semanticscholarid": "9bb33c4962a76c0841947d23279f23e6aac0da57",
        "repo": "https://anonymous.4open.science/r/EAMI-B085",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Agentmandering: A Game-Theoretic Framework for Fair Redistricting via Large Language Model Agents",
        "semanticscholarid": "53415fff609c8b1e9fb2f9f503f016f1b91a8315",
        "repo": "https://github.com/Lihaogx/AgentMandering",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AgentSHAP: Interpreting LLM Agent Tool Importance with Monte Carlo Shapley Value Estimation",
        "semanticscholarid": "36da1d21706b746604504e50ef326434822e5b3a",
        "repo": "https://github.com/GenAISHAP/TokenSHAP",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Granular Study of Safety Pretraining under Model Abliteration",
        "semanticscholarid": "cd8f896b943b7b28c65106ef0dc4ff94cb8d164f",
        "repo": "https://github.com/shashankskagnihotri/safety_pretraining",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Highly Clean Recipe Dataset with Ingredient States Annotation for State Probing Task",
        "semanticscholarid": "070ee023f567b9542cb2caafb26c543bf90fbfbb",
        "repo": "https://huggingface.co/datasets/mashi6n/nhkrecipe-100-anno-1",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A Human-Centered Mutltimodal AutoML Framework for Discriminative and Generative Tasks with Large Language Models",
        "semanticscholarid": "91121ece43de94693af15fc7ea41fa1a7a200b64",
        "repo": "https://github.com/richarf22/UniAutoML",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "A HyperGraphMamba-Based Multichannel Adaptive Model for ncRNA Classification",
        "semanticscholarid": "47583dbd910d5815059f9426b21c0614c0e4544d",
        "repo": "https://anonymous.4open.science/r/HGMamba-ncRNA-94D0",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AIGVE-MACS: Unified Multi-Aspect Commenting and Scoring Model for AI-Generated Video Evaluation",
        "semanticscholarid": "d6d7c8ab0d295985df258f653b6821e38b6295ff",
        "repo": "https://huggingface.co/xiaoliux/AIGVE-MACS",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AI-powered Immune Cell Knowledge Graph (ICKG) with granular immune contexts enables immune program interpretation",
        "semanticscholarid": "18921ce8d451d87bbae6e88056e0af549236de4e",
        "repo": "https://kchen-lab.github.io/immune-knowledgegraph.github.io/",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "AIP-TranLAC: A Transformer-Based Method Integrating LSTM and Attention Mechanism for Predicting Anti-inflammatory Peptides",
        "semanticscholarid": "afbac5d3cb445dfc8cc7680fe44fdec73b55e886",
        "repo": "https://github.com/Renjingyi123/AIP-TranLAC",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Aligned or Apart? Multi-Agent Insights into Consumer and Brand Messaging Discrepancies",
        "semanticscholarid": "4b69f469a595d88bc00d62ca760ebe4e40884c26",
        "repo": "https://github.com/htgan-ai/OPIM",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
    {
        "title": "Aligning Deep Implicit Preferences by Learning to Reason Defensively",
        "semanticscholarid": "d93c41e0223fe7f1817a0458ed8ed444f2d78d8f",
        "repo": "https://github.com/Zephyrian-Hugh/Deep-pref",
        "ground_truth": "MISSING",
        "gt_reason": "",
    },
]